# Sugstão:
# Reinicie o servidor, utilize o endpoint
# abaixo, e anote a 'Key' devolvida no 
# resultado, se tudo correr bem: É o token.
# Nos demais endpoits, ou curl, utilize o
# token recebido.


POST http://127.0.0.1:8000/registration/
Content-type: application/json

{
    "username": "astofoboldo",
    "password1": "segredo123456",
    "password2": "segredo123456"
}

### a55dd1c646dd194e33858836a190391a9ea55474


###

GET http://127.0.0.1:8000/api/appointments/
Content-type: application/json
Authorization: Token a55dd1c646dd194e33858836a190391a9ea55474

###

POST http://127.0.0.1:8000/api/appointments/
Content-type: application/json
Authorization: Token a55dd1c646dd194e33858836a190391a9ea55474

{
    "title": "Reunião",
    "description": "Com todo staff!",
    "begins_at": "2020-11-06T10:00",
    "ends_at": "2020-11-06T11:00"
}

###

DELETE http://127.0.0.1:8000/api/appointments/1/
Content-type: application/json
Authorization: Token a55dd1c646dd194e33858836a190391a9ea55474

####
curl -X GET -H "Authorization: Token 440b6465e838677a640a3f8f2be304a0cffcf412" -d ''  http://127.0.0.1:8000/api/persons/

###