# Generated by Django 3.1.2 on 2020-11-26 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agendaApp', '0002_auto_20201103_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='begins_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='ends_at',
        ),
        migrations.AddField(
            model_name='appointment',
            name='begins_at_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='begins_at_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='ends_at_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='ends_at_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
