
GET http://localhost:8000/api/persons/
Content-type: application/json
Authorization: Token 105847919578026740166

###

###

GET http://localhost:8000/api/persons/3
Content-type: application/json


###

POST http://localhost:8000/api/persons/
Content-type: application/json
Authorization: Bearer EInMhk3qJT6GZlhwdg4dakvqo5R85h

{
    "name": "Joao",
    "email": "joao@gmail.com"
}

###

curl -X POST -d "grant_type=convert_token&client_id=573611286539-37a4hn5vg53bono2kd2d48s0rkotph36.apps.googleusercontent.com&client_secret=5vLSCQARaoapdxehoK4F3R89&backend=google-oauth2&token=https://oauth2.googleapis.com/token" http://localhost:8000/auth/convert-token


###

curl -X POST -d "client_id=ZpEu5FurpNSMzlyA8mytGk0XeHXJW3ZKUryqYQTF&client_secret=mH2K61hc3HzAiSIL97UOyUSwy1dQPHZF2kovLPnWYSdTqVnqTnIlGdowZ4dvHuOhpAwHnAgHuuU6a6LlFz9MOVuqBX7n0klVI3DUFlpfCepkEp3KjPc2VtpcxPkBQY4U&grant_type=password&username=admin&password=admin" http://127.0.0.1:8000/auth/token

#"EInMhk3qJT6GZlhwdg4dakvqo5R85h"