
GET http://localhost:8000/api/persons/
Content-type: application/json

###

GET http://localhost:8000/api/persons/3
Content-type: application/json


###

POST http://localhost:8000/api/persons/
Content-type: application/json

{
    "name": "Nicotilário Abrams",
    "email": "nico@gmail.com"
}