POST http://127.0.0.1:8000/registration/
Content-type: application/json

{
    "username": "testuser",
    "password1": "testpassword",
    "password2": "testpassword"
}

###

GET http://127.0.0.1:8000/api/persons/
Content-type: application/json
Authorization: Token 6b0e82942a6afd48b9baa2b8f608a430a7c7353d

###

POST http://127.0.0.1:8000/api/persons/
Content-type: application/json
Authorization: Token 6b0e82942a6afd48b9baa2b8f608a430a7c7353d

{
    "firstName": "Astofoboldo",
    "lastName": "Neves",
    "email": "astofo@gmail.com"
}
